###Crear producto
POST http://localhost:3000/api/crear/producto
Content-Type: application/json

{
    "nombre": "AMD Laptop",
    "marca": "AMD",
    "procesador": "AMD",
    "precio": 2000,
    "cantidad": 5,
    "estado": false
}

###Obtener Productos
GET http://localhost:3000/api/productos

###Obtener producto por id
GET http://localhost:3000/api/producto/618ffed536ef040808bc7760